jdbc-config:
  host: 127.0.0.1
  port: 3306
  drive-classname: com.mysql.cj.jdbc.Driver
  database:
    user: TEST
    password: S67TtpmhiM91D8O
    name: TEST
    table-prefix: a_
    params:
      rewriteBatchedStatements: true
      useSSL: false
      serverTimezone: UTC
      allowPublicKeyRetrieval: true
  debugger: false
lib-repourl: "https://maven.aliyun.com/repository/public"

